### ISSUE TITLE
a way (API) to get the status of message?

### ISSUE THREAD

**Issue by ekoeryanto** [nats-io/node-nats-streaming#103]
Halo, I read the source and experiment with nats streaming, but I can't find a way to get the status of message. Thanks.

**Comment by aricart** [comment]
@ekoeryanto what message status are you looking for?
For nats-streaming products, the server tracks if a message has been seen by a particular subscription. In the case of durable subscriptions, the server will remember the last seen message by the specific client and resume subscriptions from that point.

Could you clarify what message status you are trying to glean?

**Comment by ekoeryanto** [comment]
Thanks for your reply.

Status of the messages or list of *nacked* messages.

Say that I have an web API `/do-payment/123` that process job _async_.
in the `/get-payment/123` I need to check whether there is a payment job for the id exists (nacked) or not

**Comment by aricart** [comment]
@ekoeryanto nats-streaming doesn't work that way (it isn't a message queue but rather a message log). Whether a message was acked or not is from the perspective of a subscription. - The subscription can be shared see [queue subscribers](https://github.com/nats-io/nats-streaming-server#queue-group) and [subscriber durability](https://github.com/nats-io/nats-streaming-server#durable).

So performing an audit by subscribing to a channel will yield all messages in the channel. Since to nats-streaming, this is a new client that hasn't seen any of the messages in the log.

A different way of looking at it using a queue and durable subscriber is that the client receiving the message doesn't ack before the configured timeout elapses, then a different subscriber will be selected by the server to process the message. Given that, you can specify a timeout that provides time for the async operation to complete, and once it completes, the client acks the message. This is a related issue in a different library https://github.com/nats-io/ts-nats/issues/39.

If you must have the audit, then likely a better pattern is to add another process in the middle that performs the verification and you easily query. So, in this case, your source channel is as it is, when the async operation completes, it publishes to a different channel with a key that can be matched to the source event.

A new streaming client would create a subscription on both the source and completed channels and create some sort of map that tracks outstanding source messages. You can then use plain nats to make a request to see the list of outstanding messages for which you have not seen a matching message on the completion channel.

**Comment by ekoeryanto** [comment]
Thanks for the reply.
> If you must have the audit, then likely a better pattern is to add another process in the middle that performs the verification and you easily query

Yes, i did it.
