### ISSUE TITLE
Request/Reply Pattern

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats-streaming#29]
Hi,
I maintain an opensource project [Hemera](https://github.com/hemerajs/hemera) which rely on gnats. I use the request/reply pattern. It's planned to implement this pattern in this lib? It would contribute the transition from gnats to NATS-Streaming? Thanks!

**Comment by aricart** [comment]
Hi There, Request Reply on streaming doesn't make much sense since effectively you are processing messages that the server already captured. This is why there's no request reply in any of the streaming libraries for NATS.

**Comment by StarpTech** [comment]
Hi, can you explain it a little bit further?

**Comment by kozlovic** [comment]
@StarpTech This is a question that comes often. We need to have a better documentation, and this topic will be covered for sure. Here is the answer I gave to someone who asked the same in the go-nats-streaming repo:

NATS Streaming is a log based system. Messages that are published to a channel stay (*) in that channel regardless of subscribers presence or if messages are consumed/acknowledged.

When you do a request/reply, the requestor has the guarantee that the subscriber received and processed the message if it gets a reply back. If no reply, it can either try to resend or give up, this is an application based decision. Having the request(s) and repl(ies) persisted generally does not make sense. Since messages are "forever" logged, any subscriber starting at a point in the log could re-process the request, and what one would do with the persisted replies?

Request calls usually uses inboxes. These would become channels that would accumulate in the server and never be removed. Inboxes being unique and potentially not known from other applications, it would even be difficult to read back from those channels.

Finally, note that the streaming API gives you access to the internal NATS connection that it uses (for instance, Go: conn.NatsConn()). You can always use that and do request/reply if you have situations where you need both streaming and regular NATS.

(*) There is limits that can be set globally or per-channel that would cause old messages to be discarded. See a given message log as a ring buffer.

**Comment by StarpTech** [comment]
@kozlovic awesome thank you!

**Comment by aricart** [comment]
Another clarification is that when you do request/reply operation, the client sets the reply subject for the request to be an inbox to which only the 'requestor' is subscribing. A 'replier' sends responses to the specified inbox. The subscription only persist for the duration of the r/r operation. Typically request operations specify the number of messages expected or an amount of time to wait for responses.

In the case of streaming, the streaming server is simply a subscriber. Its function is to record the messages received on streaming subscriptions and forward them to other streaming subscribers that expressed interest in that subject.

**Comment by StarpTech** [comment]
> Finally, note that the streaming API gives you access to the internal NATS connection that it uses (for instance, Go: conn.NatsConn()). You can always use that and do request/reply if you have situations where you need both streaming and regular NATS.

@kozlovic so NATS-streaming is just an extension for gnats right and I can use one instance for both scenarios?

**Comment by kozlovic** [comment]
NATS Streaming "server" is using NATS to communicate. See the NATS Streaming Server as a NATS client, which really is what it is. So internally it has a NATS connection to a NATS Server which by default is embedded, but Streaming can connect to standalone server.
The Streaming clients are also using a NATS client connection to communicate to the Streaming server (through NATS server). Exposing the NATS connection is just a convenience.

**Comment by StarpTech** [comment]
@kozlovic very cool I also found the answer [here](https://github.com/nats-io/nats-streaming-server/issues/178) thank you. Therefore I can easily replace at some point NATS-streaming with NATS and use both technologies. (When monitoring and clustering is supported)

**Comment by cabrinoob** [comment]
Hello,
I understood what @kozlovic said about nats streaming, but regarding the request-reply pattern, is it possible to use stream messages. For instance if we need to send a big file in the request and allow the responder to process it before while the requestor is still sending it.

**Comment by aricart** [comment]
@cabrinoob streams are a message log. Request reply is a service, you ask a question, and the response comes back. You could certainly store large data in a stream and pull it out, but you do so not by using request-reply, but by consuming the message log. Also if you are just starting to look into STAN, you should re-direct your attention towards JetStream. JetStream is now enabled into the nats-server itself.
