### ISSUE TITLE
Is it necessary to transport protobuffs as 'binary'

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats-streaming#32]
Hi, 
I'm thinking about a solution where we can use only stan to use both features of NATS-Streaming. (request/reply, pub/sub) because NATS-streaming server based on gnats. It would be useful if we could make the transport encoding agnostic.

**Comment by aricart** [comment]
A few clarifications here:

nats-streaming is encoding agnostic. Unlike plain nats, nats-streaming exchanges protobuf messages between the streaming server and the client (always). The application payload is stored in the protobuf message. You can get it as binary bytes using `Message#getRawData()`

One simplification I need to do is switch to the preseveBuffers option and see how it works. It will eliminate some encoding/decoding. With that said, encoding needs to be binary because that is what is exchanged - always.

Also note that nats streaming doesn't support request/reply. Streaming is about receiving messages that other clients published and were stored by the streaming server. There's no request interaction.

**Comment by StarpTech** [comment]
@aricart but I can use the underlying `nc` nats driver to use all methods like request/reply, publish in none streaming context ?

**Comment by aricart** [comment]
Yes you can. I rather you didn't. :)

**Comment by StarpTech** [comment]
Ok thats why I want to use one connection to cover both cases :)

**Comment by aricart** [comment]
::thumbsup::
