### ISSUE TITLE
Let's Talk About Clustering

### ISSUE THREAD

**Issue by expelledboy** [nats-io/node-nats-streaming#46]
Read clustering is in the pipeline, where can I read what thoughts have already been put into it?

I believe the best solution is to not solve it at all, and rather provide an interface to plugin consistent and redundant state engines. Imagining a combination of etc.d and cassandra.

Once an interface exists a later release can focus on a solution more tightly integrated with the requirements of this project.

**Comment by ColinSullivan1** [comment]
@expelledboy , Thank you for your interest in NATS!  We don't have any public design documents at this point.   

We are approaching meeting the requirements of clustering incrementally.  Generally, users tend to want clustering for high availability and scalability.  First, we have [Fault Tolerance](https://github.com/nats-io/nats-streaming-server#fault-tolerance) which will meet some high availability requirements of clustering.  To address scalability, we have [Partitioning](https://github.com/nats-io/nats-streaming-server#partitioning).  Partitioned streaming servers can be setup to be fault tolerant as well.

We are working on full clustering, which will be very [RAFT](https://raft.github.io/)-like, but customized with some optimizations that are allowed by the architecture of NATS streaming and because we have an least once delivery guarantee.  We are aiming to provide scalability, high performance (aggregate), and high availability with this solution.

The solution you mentioned is something we are considering, have discussed, and hope to implement (or see a contribution).  Our research so far indicates that this would not perform well compared to current file based stores.  That being said, this solution would be ideal for cases that do not require blazing speed, but a massive subject namespace (e.g. IoT).  The [store interface](https://github.com/nats-io/nats-streaming-server/blob/master/stores/store.go#L137) is where one would start if implementing a store.  Can you expand on your thoughts?

We've started an issue related to this here: #https://github.com/nats-io/nats-streaming-server/issues/168

**Comment by aricart** [comment]
This discussion is really about the streaming server, not the node-streaming client. Please add additional comments to nats-io/nats-streaming-server#168. Thanks!
