### ISSUE TITLE
stan.publish() can "publish" message before connection is established

### ISSUE THREAD

**Issue by holem** [nats-io/node-nats-streaming#54]
Hello,
We've found that the library allows to call `stan.publish()` without any errors (and even guid was assigned) before the connection to the server was established. As a result, the application "thinks" the message was sent and wait for response, but in fact nothing happened.

Is there a way to check the connection status before sending messages? Something like this:
```
if (stan.isConnected()) {
    await stan.publish(...)
} else {
    stan.on("connect", function() {
        stan.publish(...)
    });
}
```
Or even do this automatically by the library, i.e. when the user tries to publish message before the connection is established, the sending is delayed until the connection event will be dispatched.
Thanks.

**Comment by ksmithut** [comment]
So far, we've had to build our own wrapper "class" (not really a class) that you call `.connect()` on, but you can call `.publish`, but it will just queue up the publish calls until connect is finished. What we actually do is initialize an unresolved promise (deferred promise), then connect is called, we call the `.connect()` method, then when that finishes, we resolve the deferred promise. Then we have a `.publish` function on the class that waits until the deferred promise is resolved until it actually publishes. This is still a naive approach because it doesn't handle the case of waiting for the connection to reconnect in the case that the client disconnects from the nats server, but it gets the process down.

I would very much rather have that logic live within this library because shallow wrappers tend to be brittle.

**Comment by aricart** [comment]
@ksmithut @holem , have you tried registering a 'connect' listener on stan?
The connect notification goes out after the prefixes used by the streaming protocol have been received by the client. Note the connect handler should be set on stan, not nats. The nats connection also has a `connect` notification, but this is on connecting to nats which happens before the streaming protocol is initialized.

```
var stan = require('../lib/stan.js').connect(cluster_id, client_id, server);
stan.on('connect', function() {
  start();
});

stan.on('error', function(reason) {
  console.log(reason);
});

function start() {
  stan.publish(subject ....
});
```

**Comment by ksmithut** [comment]
The issue comes in because a publish event happens someplace else, sometimes in a request handler. I don't think I've ever written a nats client that just connects and immediately publishes an event. Events typically get published as a result of an API endpoint call, or something like that. So when the server starts, it starts the connection, but the requests happen asynchronously from the connection event. Meaning, to do what you're proposing, I'd have to write something like this:

```
const express = require('express')

const app = express()

stan.on('connect', () => {
  app.get('/api-endpoint', (req, res, next) => {
    // do noteworthy things
    stan.publish(subject, ...)
  })

  // add in all of the rest of my endpoints, dozens, hundreds maybe

  app.listen(PORT)
})
```

There are ways to pass that stan object around, but it would make nats-streaming-server kind of take over the architecture of my code, when I really just wanted to start eventing as a side thing. `mongoose` handles this sort of thing really well, where you can initiate the connection, but at the same time be queuing up calls until the connection is made with some sort of in-memory buffer. I think it's optional, but in the use case of actually making calls as a result of a direct api call, the connection is still much more likely to happen before any requests make it through.

**Comment by aricart** [comment]
@ksmithut,  I think your handler can be a lot simpler, you don't have to restructure your application. You can fully configure your express application as you do now. The `app.listen(PORT);`  is the only code that needs to happen within the `connect` notification handler. 

I will discuss with the group. But my take is that your application is not fully initialized. Likely the simpler architecture of not accepting clients is easier to scale because it will make whoever holds data responsible for it for the duration. In the case of a server, the many clients could be serviced only to have their data lost.
