### ISSUE TITLE
Request/reply?

### ISSUE THREAD

**Issue by shaneiseminger** [nats-io/node-nats-streaming#6]
I'm attempting to implement this library using request/reply. I seem to be able to reply on the subscription end fine, but I'm not seeing a way to receive that reply on the publisher side. I tried using plain `node-nats` on the publisher side but that doesn't seem to ever fire the response callback.

Is there a way to do this with this library, or will there be a way to do it in the future? Or am I missing some fundamental concept? I understand this library is a work in progress, I don't intend to sound pushy.

**Comment by aricart** [comment]
Currently some of the other clients for nats-streaming are implementing request-reply. But there's on-going discussion as whether the meaning of request-reply in a streaming context makes sense. Current group consensus is that request-reply in a streaming context is meaningless and it is possible that the client API in the other libraries will be retracted. The node-nats-streaming implemented it but later removed it in order to avoid the deprecation.

A little background. Typically a request operation is in a specific context where a response is expected. This means that a request where the requestor goes away only to re-subscribe to get responses is likely not a correct use case. Even if the requestor disconnected, it could on re-connect to make another request.

A better strategy/practice is to use a non-streaming (node-nats) connection and perform requests reply interactions from there. Note that while node-nats-streaming supports sharing a nats connection, it expects the connection to have a 'binary' payload. As the protobufs used to format the streaming messages requires that. For that reason, you should simply create a regular nats connection to the server instead of attempting to share it.

If you have some use case that can help us motivate its inclusion, please feel free to respond and comment.

**Comment by shaneiseminger** [comment]
Thanks, appreciate the information.

My case is fairly pragmatic: I want to send messages to workers for processing and have them respond with the results. The publisher then takes the appropriate action, usually storing the results of that action in a database.

Obviously I can just as easily have the workers store the results themselves, and I can build some kind of job acknowledgement into that part of the worker too. I had been pursuing having that on the publisher side because it would mean fewer database connections hanging around. But given that the state of request/reply is in flux, I'll move forward with the worker option.

**Comment by aricart** [comment]
I had a short meeting with other folks to talk about this. And support for request-reply was also removed from C# client. So yes the functionality is not going to be there.

Can you describe why you think you would have more db connections? This sound like an application pattern issue.

**Comment by shaneiseminger** [comment]
_n_ workers = _n_ database connections. Because of the type of workload, a single worker will occupy a single container even when processing many payloads.

It's a minor issue and not really one that can't be solved with a somewhat larger database instance, plus not one I expect will occur without a very high number of workers running in the system, which will not be the case for some time, if ever. So while it's nice to design for that kind of scale, I'm not too concerned about it.

**Comment by aricart** [comment]
One pattern you could use it to provide a database proxy, this worker could
be part of a queue group, and only this type of worker connects to the
database and consumes database events. Then you can scale your database
connections as needed, but they are not tied to the other workers you have.


On September 12, 2016 at 4:54:34 PM, shaneiseminger (
notifications@github.com) wrote:

*n* workers = *n* database connections. Because of the type of workload, a
single worker will occupy a single container even when processing many
payloads.

It's a minor issue and not really one that can't be solved with a somewhat
larger database instance, plus not one I expect will occur without a very
high number of workers running in the system, which will not be the case
for some time, if ever. So while it's nice to design for that kind of
scale, I'm not too concerned about it.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/nats-io/node-nats-streaming/issues/6#issuecomment-246507090>,
or mute the thread

**Comment by shaneiseminger** [comment]
That's a good idea, I'll definitely look into that. Thanks!
